
lss_baseline:
  config: 'configs/eval_carla_lss_baseline.yaml'
  path: 'carla/lss_baseline/model13000.pt'
  label: 'LSS Baseline'

lss_enn:
  config: 'configs/eval_carla_lss_enn.yaml'
  path: 'carla/lss_enn/model13000.pt'
  label: 'LSS Evidential'

lss_postnet:
  config: 'configs/eval_carla_lss_postnet.yaml'
  path: 'carla/lss_postnet/model13000.pt'
  label: 'LSS Postnet'

lss_dropout:
  config: 'configs/eval_carla_lss_dropout.yaml'
  path: 'carla/lss_dropout/model13000.pt'
  label: 'LSS MC Dropout'

lss_ensemble:
  config: 'configs/eval_carla_lss_ensemble.yaml'
  path: 'carla/lss_ensemble/model13000.pt'
  label: 'LSS Ensemble'

cvt_baseline:
  config: 'configs/eval_carla_cvt_baseline.yaml'
  path: 'carla/cvt_baseline/model10000.pt'
  label: 'CVT Baseline'

cvt_enn:
  config: 'configs/eval_carla_cvt_enn.yaml'
  path: 'carla/cvt_enn/model8000.pt'
  label: 'CVT Evidential'

cvt_postnet:
  config: 'configs/eval_carla_cvt_postnet.yaml'
  path: 'carla/cvt_postnet/model7000.pt'
  label: 'CVT Postnet'

cvt_dropout:
  config: 'configs/eval_carla_cvt_dropout.yaml'
  path: 'carla/cvt_dropout/model10000.pt'
  label: 'CVT MC Dropout'

cvt_ensemble:
  config: 'configs/eval_carla_cvt_ensemble.yaml'
  path: 'carla/cvt_ensemble/model10000.pt'
  label: 'CVT Ensemble'
