
cvt_baseline:
  config: 'configs/eval_nuscenes_cvt_baseline.yaml'
  path: 'nuscenes/cvt_baseline/model20000.pt'
  label: "CVT Baseline"

cvt_enn:
  config: 'configs/eval_nuscenes_cvt_enn.yaml'
  path: 'nuscenes/cvt_enn/model19000.pt'
  label: "CVT Evidential"

cvt_postnet:
  config: 'configs/eval_nuscenes_cvt_postnet.yaml'
  path: 'nuscenes/cvt_postnet/model20000.pt'
  label: "CVT Postnet"

cvt_dropout:
  config: 'configs/eval_nuscenes_cvt_dropout.yaml'
  path: 'nuscenes/cvt_dropout/model18000.pt'
  label: "CVT Dropout"

#cvt_ensemble:
#  config: 'configs/eval_carla_cvt_ensemble.yaml'
#  path: 'carla/cvt_ensemble/model7000.pt'
#  label: "CVT Ensemble"