type: 'ensemble'
backbone: 'lss'
dataset: 'carla'
logdir: './carla/lss_ensemble_gtseg'
gpus: [0]
batch_size: 8
num_workers: 16
model_path: 'carla/lss_ensemble_gtseg/best_iou.pt'
tsne: false
seg: true
