type: 'baseline'
backbone: 'lss'
dataset: 'carla'
logdir: './carla/lss_baseline_gtseg'
gpus: [0]
batch_size: 8
num_workers: 16
model_path: 'carla/lss_baseline_gtseg/model15000.pt'
tsne: false
seg: true